import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1768924875328 implements MigrationInterface {
    name = 'InitialSchema1768924875328'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'artist', 'normal')`);
        await queryRunner.query(`CREATE TYPE "public"."users_subscription_enum" AS ENUM('free', 'independent', 'pro', 'label')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying, "name" character varying NOT NULL, "isEmailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "emailVerificationTokenExpiration" TIMESTAMP, "resetToken" character varying, "resetTokenExpiration" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "role" "public"."users_role_enum" NOT NULL DEFAULT 'normal', "profile" character varying, "profileImage" text, "phoneNumber" character varying, "country" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "subscription" "public"."users_subscription_enum" NOT NULL DEFAULT 'free', "google_id" character varying, "spotify_id" character varying, "tokenVersion" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resetCode" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_838af121380dfe3a6330e04f5bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "UQ_3d1613f95c6a564a3b588d161ae" UNIQUE ("token"), CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d1613f95c6a564a3b588d161a" ON "email_verification_tokens" ("token") `);
        await queryRunner.query(`CREATE TABLE "otp" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, "userId" uuid, CONSTRAINT "PK_32556d9d7b22031d7d0e1fd6723" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "labels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "labelName" character varying NOT NULL, "legalEntityName" character varying NOT NULL, "logo" character varying, "bio" text, "genres" text NOT NULL, "socialMediaLinks" jsonb NOT NULL, "website" character varying, "contactInformation" jsonb NOT NULL, "taxId" character varying, "businessRegistrationNumber" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid, CONSTRAINT "UQ_5eddf31e3975cb712baad7d6341" UNIQUE ("labelName"), CONSTRAINT "PK_c0c4e97f76f1f3a268c7a70b925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "artists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "country" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "website" character varying, "genres" text NOT NULL, "bio" text, "musicPlatforms" jsonb NOT NULL, "socialMediaLinks" jsonb NOT NULL, "userId" uuid, "labelId" uuid, CONSTRAINT "PK_09b823d4607d2675dc4ffa82261" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "temp_artists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "hasStreamingPresence" boolean NOT NULL DEFAULT false, "spotifyUrl" character varying, "appleMusicUrl" character varying, "youtubeUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_120550a6fca5a95aec2d2bf74d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."release_containers_type_enum" AS ENUM('EP', 'ALBUM')`);
        await queryRunner.query(`CREATE TYPE "public"."release_containers_status_enum" AS ENUM('DRAFT', 'IN_PROGRESS', 'COMPLETE', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED')`);
        await queryRunner.query(`CREATE TABLE "release_containers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "type" "public"."release_containers_type_enum" NOT NULL, "releaseLanguage" character varying NOT NULL, "primaryGenre" character varying NOT NULL, "secondaryGenres" text, "recordingYear" integer NOT NULL, "upc" character varying, "catalogNumber" character varying, "description" text, "totalTracks" integer NOT NULL, "uploadedTracks" integer NOT NULL DEFAULT '0', "lastUploadedTrackNumber" integer, "completedAt" TIMESTAMP, "label" character varying NOT NULL, "coverArtId" character varying NOT NULL, "originalReleaseDate" TIMESTAMP, "proposedReleaseDate" TIMESTAMP NOT NULL, "releaseTime" character varying NOT NULL, "isPreOrder" boolean NOT NULL DEFAULT false, "preOrderDate" TIMESTAMP, "price" numeric(10,2) NOT NULL, "targetStores" text NOT NULL, "targetCountries" text NOT NULL, "status" "public"."release_containers_status_enum" NOT NULL DEFAULT 'DRAFT', "reviewNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "uploadedById" uuid, "isExplicit" boolean NOT NULL DEFAULT false, "primaryArtistId" uuid, CONSTRAINT "PK_e861471b8e2d4b68e658b46ef61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."songs_releasetype_enum" AS ENUM('SINGLE', 'ALBUM', 'EP')`);
        await queryRunner.query(`CREATE TYPE "public"."songs_status_enum" AS ENUM('DRAFT', 'PENDING_REVIEW', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', 'TAKEN_DOWN')`);
        await queryRunner.query(`CREATE TABLE "songs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "releaseType" "public"."songs_releasetype_enum" NOT NULL, "releaseLanguage" character varying NOT NULL, "label" character varying NOT NULL, "primaryGenre" character varying NOT NULL, "secondaryGenres" text, "recordingYear" integer NOT NULL, "isExplicit" boolean NOT NULL DEFAULT false, "isrc" character varying, "description" text, "coverArtId" character varying NOT NULL, "masterTrackId" character varying NOT NULL, "mixVersions" jsonb, "previewClip" jsonb, "musicVideo" jsonb, "originalReleaseDate" TIMESTAMP, "proposedReleaseDate" TIMESTAMP NOT NULL, "releaseTime" character varying NOT NULL, "isPreOrder" boolean NOT NULL DEFAULT false, "preOrderDate" TIMESTAMP, "trackPrice" numeric(10,2) NOT NULL, "targetStores" text NOT NULL, "targetCountries" text NOT NULL, "status" "public"."songs_status_enum" NOT NULL DEFAULT 'DRAFT', "reviewNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "currentSplitSheetId" uuid, "releaseContainerId" uuid, "trackNumber" integer, "uploadedById" uuid, "primaryArtistId" uuid, CONSTRAINT "PK_e504ce8ad2e291d3a1d8f1ea2f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."collaborators_role_enum" AS ENUM('Producer', 'Writer', 'Composer', 'Lyricist', 'Mix Engineer', 'Mastering Engineer', 'Featured Artist', 'Remixer', 'Musician', 'Arranger', 'Other')`);
        await queryRunner.query(`CREATE TABLE "collaborators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "songId" uuid NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "role" "public"."collaborators_role_enum" NOT NULL, "creditedAs" character varying, "spotifyUrl" character varying, "appleUrl" character varying, "youtubeUrl" character varying, "displayOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "createdByUserId" uuid, CONSTRAINT "PK_f579a5df9d66287f400806ad875" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lyrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "basicLyrics" text NOT NULL, "synchronizedLyrics" jsonb NOT NULL DEFAULT '[]', "songId" uuid NOT NULL, "version" integer NOT NULL, "isComplete" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying NOT NULL, "updatedBy" character varying NOT NULL, CONSTRAINT "PK_f7c5de22ef94f309591c5554f0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."files_status_enum" AS ENUM('pending', 'processing', 'complete', 'failed', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."files_validationstatus_enum" AS ENUM('pending', 'in_progress', 'passed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "originalFilename" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" bigint NOT NULL, "path" character varying NOT NULL, "bucket" character varying NOT NULL, "key" character varying NOT NULL, "status" "public"."files_status_enum" NOT NULL DEFAULT 'pending', "validationStatus" "public"."files_validationstatus_enum" NOT NULL DEFAULT 'pending', "metadata" jsonb, "validationResults" jsonb, "processingResults" jsonb, "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "lastAccessedAt" TIMESTAMP, "downloadCount" integer NOT NULL DEFAULT '0', "storageKey" character varying NOT NULL, "uploadedById" uuid, CONSTRAINT "UQ_f734c17eff711279fdda38cc4ae" UNIQUE ("storageKey"), CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audio_files_status_enum" AS ENUM('pending', 'processing', 'complete', 'failed', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."audio_files_validationstatus_enum" AS ENUM('pending', 'in_progress', 'passed', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."audio_files_format_enum" AS ENUM('mp3', 'wav', 'flac', 'aac', 'ogg')`);
        await queryRunner.query(`CREATE TYPE "public"."audio_files_quality_enum" AS ENUM('master', 'high', 'standard', 'preview')`);
        await queryRunner.query(`CREATE TABLE "audio_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "originalFilename" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" bigint NOT NULL, "path" character varying NOT NULL, "bucket" character varying NOT NULL, "key" character varying NOT NULL, "status" "public"."audio_files_status_enum" NOT NULL DEFAULT 'pending', "validationStatus" "public"."audio_files_validationstatus_enum" NOT NULL DEFAULT 'pending', "metadata" jsonb, "validationResults" jsonb, "processingResults" jsonb, "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "lastAccessedAt" TIMESTAMP, "downloadCount" integer NOT NULL DEFAULT '0', "storageKey" character varying NOT NULL, "format" "public"."audio_files_format_enum" NOT NULL, "quality" "public"."audio_files_quality_enum" NOT NULL DEFAULT 'master', "duration" integer NOT NULL, "bitrate" integer NOT NULL, "sampleRate" integer NOT NULL, "channels" integer NOT NULL, "waveform" jsonb, "loudness" double precision, "spectrum" jsonb, "encoderSettings" character varying, "analysis" jsonb, "hasClipping" boolean NOT NULL DEFAULT false, "isNormalized" boolean NOT NULL DEFAULT false, "masterVersionId" character varying, "uploadedById" uuid, CONSTRAINT "UQ_2557a7d44257288d803c01f0120" UNIQUE ("storageKey"), CONSTRAINT "PK_687c178ef33b4e0e1f83ae66cbb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."image_files_status_enum" AS ENUM('pending', 'processing', 'complete', 'failed', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."image_files_validationstatus_enum" AS ENUM('pending', 'in_progress', 'passed', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."image_files_format_enum" AS ENUM('jpeg', 'png', 'webp', 'gif', 'svg')`);
        await queryRunner.query(`CREATE TYPE "public"."image_files_sizetype_enum" AS ENUM('original', 'large', 'medium', 'small', 'thumbnail')`);
        await queryRunner.query(`CREATE TABLE "image_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "originalFilename" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" bigint NOT NULL, "path" character varying NOT NULL, "bucket" character varying NOT NULL, "key" character varying NOT NULL, "status" "public"."image_files_status_enum" NOT NULL DEFAULT 'pending', "validationStatus" "public"."image_files_validationstatus_enum" NOT NULL DEFAULT 'pending', "metadata" jsonb, "validationResults" jsonb, "processingResults" jsonb, "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "lastAccessedAt" TIMESTAMP, "downloadCount" integer NOT NULL DEFAULT '0', "storageKey" character varying NOT NULL, "format" "public"."image_files_format_enum" NOT NULL, "sizeType" "public"."image_files_sizetype_enum" NOT NULL DEFAULT 'original', "width" integer NOT NULL, "height" integer NOT NULL, "dpi" integer, "colorSpace" character varying, "bitDepth" integer, "hasAlpha" boolean NOT NULL DEFAULT false, "colorProfile" jsonb, "compression" jsonb, "analysis" jsonb, "originalVersionId" character varying, "uploadedById" uuid, CONSTRAINT "UQ_25ee2025fdac4a1307377409e64" UNIQUE ("storageKey"), CONSTRAINT "PK_2fa5a07f4784790123c4bf07f41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."video_files_status_enum" AS ENUM('pending', 'processing', 'complete', 'failed', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."video_files_validationstatus_enum" AS ENUM('pending', 'in_progress', 'passed', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."video_files_format_enum" AS ENUM('mp4', 'mov', 'avi', 'mkv', 'webm')`);
        await queryRunner.query(`CREATE TYPE "public"."video_files_quality_enum" AS ENUM('master', 'hd', 'sd', 'low', 'preview')`);
        await queryRunner.query(`CREATE TABLE "video_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "originalFilename" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" bigint NOT NULL, "path" character varying NOT NULL, "bucket" character varying NOT NULL, "key" character varying NOT NULL, "status" "public"."video_files_status_enum" NOT NULL DEFAULT 'pending', "validationStatus" "public"."video_files_validationstatus_enum" NOT NULL DEFAULT 'pending', "metadata" jsonb, "validationResults" jsonb, "processingResults" jsonb, "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "lastAccessedAt" TIMESTAMP, "downloadCount" integer NOT NULL DEFAULT '0', "storageKey" character varying NOT NULL, "format" "public"."video_files_format_enum" NOT NULL, "quality" "public"."video_files_quality_enum" NOT NULL DEFAULT 'master', "duration" integer NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "frameRate" double precision NOT NULL, "bitrate" integer NOT NULL, "videoStream" jsonb NOT NULL, "audioStream" jsonb, "encodingSettings" jsonb, "analysis" jsonb, "thumbnailKey" character varying, "masterVersionId" character varying, "uploadedById" uuid, CONSTRAINT "UQ_27ff4a02eb7b5a896f0a62aeaee" UNIQUE ("storageKey"), CONSTRAINT "PK_bbf7ca354ae34a4d1fd3f4a5a1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "uploadId" character varying NOT NULL, "chunkNumber" integer NOT NULL, "totalChunks" integer NOT NULL, "chunkSize" integer NOT NULL, "storageKey" character varying NOT NULL, "metadata" jsonb, "uploaded" boolean NOT NULL DEFAULT false, "error" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP, "fileId" uuid, CONSTRAINT "PK_a2c49176d54c6ad7d6c6b841afa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."split_sheets_status_enum" AS ENUM('Active', 'PaidOut', 'Archived')`);
        await queryRunner.query(`CREATE TABLE "split_sheets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."split_sheets_status_enum" NOT NULL DEFAULT 'Active', "paidOutAt" TIMESTAMP, "lastModifiedBy" character varying, "previousVersionId" uuid, "version" integer NOT NULL DEFAULT '1', "replacedAt" TIMESTAMP, "replacedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "songId" uuid, CONSTRAINT "PK_808a497d6ebf2107160dc14b965" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."split_sheet_entries_status_enum" AS ENUM('Pending', 'Active', 'Paid', 'Invalidated')`);
        await queryRunner.query(`CREATE TABLE "split_sheet_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "splitSheetId" uuid NOT NULL, "userId" uuid, "recipientEmail" character varying NOT NULL, "recipientName" character varying, "claimToken" character varying NOT NULL, "percentage" numeric(5,2) NOT NULL, "status" "public"."split_sheet_entries_status_enum" NOT NULL DEFAULT 'Pending', "invalidatedAt" TIMESTAMP, CONSTRAINT "UQ_13e9bada243e8e983e9d6f10ab2" UNIQUE ("claimToken"), CONSTRAINT "PK_d4d1d86bcb47a6680dd15204a88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payout_methods_type_enum" AS ENUM('paypal', 'bank', 'wire')`);
        await queryRunner.query(`CREATE TABLE "payout_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."payout_methods_type_enum" NOT NULL, "paypalEmail" character varying, "accountName" character varying, "accountNumber" character varying, "routingNumber" character varying, "bankName" character varying, "swiftCode" character varying, "bankAddress" character varying, "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cedb0a9e379a9a0a16ad050527e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ratedfans_pages_releasetype_enum" AS ENUM('Single', 'EP', 'Album', 'Mixtape', 'Live', 'Remix')`);
        await queryRunner.query(`CREATE TABLE "ratedfans_pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "releaseTitle" character varying NOT NULL, "artistName" character varying, "artistId" uuid NOT NULL, "songId" uuid, "isPublished" boolean NOT NULL DEFAULT false, "isPresaveEnabled" boolean NOT NULL DEFAULT false, "releaseDate" TIMESTAMP, "releaseType" "public"."ratedfans_pages_releasetype_enum", "socialMediaLinks" jsonb, "previewClips" jsonb, "coverArtLink" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_95f5b723edb71e0b2425899cb5b" UNIQUE ("slug"), CONSTRAINT "PK_4cc881ce092f0bfc1d50d05123f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_95f5b723edb71e0b2425899cb5" ON "ratedfans_pages" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_ratedfans_pages_published" ON "ratedfans_pages" ("isPublished") `);
        await queryRunner.query(`CREATE INDEX "idx_ratedfans_pages_artist_song" ON "ratedfans_pages" ("artistId", "songId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_ratedfans_pages_slug" ON "ratedfans_pages" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."ratedfans_links_platform_enum" AS ENUM('spotify', 'appleMusic', 'youtubeMusic', 'deezer', 'tidal', 'audiomack', 'iHeartRadio', 'amazonMusic', 'iTunes', 'vevo')`);
        await queryRunner.query(`CREATE TABLE "ratedfans_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pageId" uuid NOT NULL, "platform" "public"."ratedfans_links_platform_enum" NOT NULL, "url" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isPrimary" boolean NOT NULL DEFAULT false, "displayOrder" integer, "releaseDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca94a2c46e0e0fdef3b559c5ebb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ratedfans_links_active" ON "ratedfans_links" ("isActive") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_ratedfans_links_page_platform" ON "ratedfans_links" ("pageId", "platform") `);
        await queryRunner.query(`CREATE TYPE "public"."presave_signups_platform_enum" AS ENUM('spotify', 'appleMusic', 'youtubeMusic', 'deezer', 'tidal', 'audiomack', 'iHeartRadio', 'amazonMusic', 'iTunes', 'vevo')`);
        await queryRunner.query(`CREATE TYPE "public"."presave_signups_status_enum" AS ENUM('pending', 'confirmed', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "presave_signups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pageId" uuid NOT NULL, "email" character varying NOT NULL, "platform" "public"."presave_signups_platform_enum" NOT NULL, "status" "public"."presave_signups_status_enum" NOT NULL DEFAULT 'pending', "confirmationToken" character varying, "confirmedAt" TIMESTAMP, "notifiedAt" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3768080e9fe074f0096f292dbd4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_presave_signups_platform" ON "presave_signups" ("platform") `);
        await queryRunner.query(`CREATE INDEX "idx_presave_signups_status" ON "presave_signups" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_presave_signups_page_email" ON "presave_signups" ("pageId", "email") `);
        await queryRunner.query(`CREATE TABLE "promo_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pageId" uuid NOT NULL, "fileUrl" character varying NOT NULL, "fileName" character varying NOT NULL, "size" bigint NOT NULL, "mimeType" character varying, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4c52194dbe499a9ab512ebc4696" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_promo_cards_page" ON "promo_cards" ("pageId") `);
        await queryRunner.query(`CREATE TABLE "release_container_featured_artists" ("container_id" uuid NOT NULL, "artist_id" uuid NOT NULL, CONSTRAINT "PK_56fe618399120d4edebb0d3a27c" PRIMARY KEY ("container_id", "artist_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f642e9450e265bc8e8874c9fe" ON "release_container_featured_artists" ("container_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b391b3cae8cd5e3e097e914ad" ON "release_container_featured_artists" ("artist_id") `);
        await queryRunner.query(`CREATE TABLE "release_container_featured_temp_artists" ("container_id" uuid NOT NULL, "temp_artist_id" uuid NOT NULL, CONSTRAINT "PK_b6ebcbe925f790bf92659fa6910" PRIMARY KEY ("container_id", "temp_artist_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4768f3456814c77f3f16346f64" ON "release_container_featured_temp_artists" ("container_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_324141f738c918793a4b925766" ON "release_container_featured_temp_artists" ("temp_artist_id") `);
        await queryRunner.query(`CREATE TABLE "song_featured_artists" ("song_id" uuid NOT NULL, "artist_id" uuid NOT NULL, CONSTRAINT "PK_9bd3b0b82f79b654bb7b4fcbf58" PRIMARY KEY ("song_id", "artist_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a3748b7c54e518df2e26acfcc9" ON "song_featured_artists" ("song_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b69e21df84c9ad1d583b39ed7e" ON "song_featured_artists" ("artist_id") `);
        await queryRunner.query(`CREATE TABLE "song_featured_temp_artists" ("song_id" uuid NOT NULL, "temp_artist_id" uuid NOT NULL, CONSTRAINT "PK_04c29d23f27c4db22ca4b7ec560" PRIMARY KEY ("song_id", "temp_artist_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad75ed868b666dc10ccd8ae856" ON "song_featured_temp_artists" ("song_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a2a9ebf4ad76daa68a1928f56" ON "song_featured_temp_artists" ("temp_artist_id") `);
        await queryRunner.query(`ALTER TABLE "password_reset_token" ADD CONSTRAINT "FK_a4e53583f7a8ab7d01cded46a41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_10f285d038feb767bf7c2da14b3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp" ADD CONSTRAINT "FK_db724db1bc3d94ad5ba38518433" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_f31f88025417e09223ea9a66b0b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_f7bd9114dc2849a90d39512911b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_539df2da3266ea3be5107f73a4b" FOREIGN KEY ("labelId") REFERENCES "labels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_containers" ADD CONSTRAINT "FK_81b31b9899b0dcf42037a0486c8" FOREIGN KEY ("primaryArtistId") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_containers" ADD CONSTRAINT "FK_0653392b8b9a0b778449afb8507" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "songs" ADD CONSTRAINT "FK_3ea40af60e7deab5fe355995969" FOREIGN KEY ("primaryArtistId") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "songs" ADD CONSTRAINT "FK_5789c0783b7d8fff2eda1e2b1a5" FOREIGN KEY ("currentSplitSheetId") REFERENCES "split_sheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "songs" ADD CONSTRAINT "FK_dc7e3bd7dd229d873f0d4a4b0e6" FOREIGN KEY ("releaseContainerId") REFERENCES "release_containers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "songs" ADD CONSTRAINT "FK_277ccc2a69a45fe1c39291b05bb" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collaborators" ADD CONSTRAINT "FK_8124c8d02e6d4729ebbd10f94fa" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collaborators" ADD CONSTRAINT "FK_4c40b1058f7e2b07e2e8b5dc4a2" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lyrics" ADD CONSTRAINT "FK_1929e3cdc8b3e28106e773b16d6" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a525d85f0ac59aa9a971825e1af" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audio_files" ADD CONSTRAINT "FK_f0c1a412a45bb25fb409a75d21f" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_files" ADD CONSTRAINT "FK_bdd377e4be046c911f68fe51da9" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_files" ADD CONSTRAINT "FK_3de327d0c71c191f9cb36b2ce1e" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_chunks" ADD CONSTRAINT "FK_fa6b569d259975a6e35a7851c69" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "split_sheets" ADD CONSTRAINT "FK_6fd198aec672ad50d8b4d1d6eab" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "split_sheet_entries" ADD CONSTRAINT "FK_b416c09d151e75d358488f5489e" FOREIGN KEY ("splitSheetId") REFERENCES "split_sheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "split_sheet_entries" ADD CONSTRAINT "FK_38c0308e21c6f2037372ec4b41e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payout_methods" ADD CONSTRAINT "FK_372920d813ceab29336fc5221e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratedfans_pages" ADD CONSTRAINT "FK_2ab0182cbd7520f3f238d9c1d43" FOREIGN KEY ("artistId") REFERENCES "artists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratedfans_pages" ADD CONSTRAINT "FK_a024321337ca85057640a94d9c2" FOREIGN KEY ("songId") REFERENCES "songs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratedfans_links" ADD CONSTRAINT "FK_b391f6fccce712ebdc8b45cab0c" FOREIGN KEY ("pageId") REFERENCES "ratedfans_pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presave_signups" ADD CONSTRAINT "FK_7d3fc4798134fdb4272866cb593" FOREIGN KEY ("pageId") REFERENCES "ratedfans_pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promo_cards" ADD CONSTRAINT "FK_c02105bfcfd524bb03671380431" FOREIGN KEY ("pageId") REFERENCES "ratedfans_pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_artists" ADD CONSTRAINT "FK_3f642e9450e265bc8e8874c9fe2" FOREIGN KEY ("container_id") REFERENCES "release_containers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_artists" ADD CONSTRAINT "FK_9b391b3cae8cd5e3e097e914ad6" FOREIGN KEY ("artist_id") REFERENCES "artists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_temp_artists" ADD CONSTRAINT "FK_4768f3456814c77f3f16346f646" FOREIGN KEY ("container_id") REFERENCES "release_containers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_temp_artists" ADD CONSTRAINT "FK_324141f738c918793a4b9257662" FOREIGN KEY ("temp_artist_id") REFERENCES "temp_artists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_featured_artists" ADD CONSTRAINT "FK_a3748b7c54e518df2e26acfcc97" FOREIGN KEY ("song_id") REFERENCES "songs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_featured_artists" ADD CONSTRAINT "FK_b69e21df84c9ad1d583b39ed7e2" FOREIGN KEY ("artist_id") REFERENCES "artists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_featured_temp_artists" ADD CONSTRAINT "FK_ad75ed868b666dc10ccd8ae8561" FOREIGN KEY ("song_id") REFERENCES "songs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "song_featured_temp_artists" ADD CONSTRAINT "FK_0a2a9ebf4ad76daa68a1928f567" FOREIGN KEY ("temp_artist_id") REFERENCES "temp_artists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "song_featured_temp_artists" DROP CONSTRAINT "FK_0a2a9ebf4ad76daa68a1928f567"`);
        await queryRunner.query(`ALTER TABLE "song_featured_temp_artists" DROP CONSTRAINT "FK_ad75ed868b666dc10ccd8ae8561"`);
        await queryRunner.query(`ALTER TABLE "song_featured_artists" DROP CONSTRAINT "FK_b69e21df84c9ad1d583b39ed7e2"`);
        await queryRunner.query(`ALTER TABLE "song_featured_artists" DROP CONSTRAINT "FK_a3748b7c54e518df2e26acfcc97"`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_temp_artists" DROP CONSTRAINT "FK_324141f738c918793a4b9257662"`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_temp_artists" DROP CONSTRAINT "FK_4768f3456814c77f3f16346f646"`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_artists" DROP CONSTRAINT "FK_9b391b3cae8cd5e3e097e914ad6"`);
        await queryRunner.query(`ALTER TABLE "release_container_featured_artists" DROP CONSTRAINT "FK_3f642e9450e265bc8e8874c9fe2"`);
        await queryRunner.query(`ALTER TABLE "promo_cards" DROP CONSTRAINT "FK_c02105bfcfd524bb03671380431"`);
        await queryRunner.query(`ALTER TABLE "presave_signups" DROP CONSTRAINT "FK_7d3fc4798134fdb4272866cb593"`);
        await queryRunner.query(`ALTER TABLE "ratedfans_links" DROP CONSTRAINT "FK_b391f6fccce712ebdc8b45cab0c"`);
        await queryRunner.query(`ALTER TABLE "ratedfans_pages" DROP CONSTRAINT "FK_a024321337ca85057640a94d9c2"`);
        await queryRunner.query(`ALTER TABLE "ratedfans_pages" DROP CONSTRAINT "FK_2ab0182cbd7520f3f238d9c1d43"`);
        await queryRunner.query(`ALTER TABLE "payout_methods" DROP CONSTRAINT "FK_372920d813ceab29336fc5221e6"`);
        await queryRunner.query(`ALTER TABLE "split_sheet_entries" DROP CONSTRAINT "FK_38c0308e21c6f2037372ec4b41e"`);
        await queryRunner.query(`ALTER TABLE "split_sheet_entries" DROP CONSTRAINT "FK_b416c09d151e75d358488f5489e"`);
        await queryRunner.query(`ALTER TABLE "split_sheets" DROP CONSTRAINT "FK_6fd198aec672ad50d8b4d1d6eab"`);
        await queryRunner.query(`ALTER TABLE "file_chunks" DROP CONSTRAINT "FK_fa6b569d259975a6e35a7851c69"`);
        await queryRunner.query(`ALTER TABLE "video_files" DROP CONSTRAINT "FK_3de327d0c71c191f9cb36b2ce1e"`);
        await queryRunner.query(`ALTER TABLE "image_files" DROP CONSTRAINT "FK_bdd377e4be046c911f68fe51da9"`);
        await queryRunner.query(`ALTER TABLE "audio_files" DROP CONSTRAINT "FK_f0c1a412a45bb25fb409a75d21f"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a525d85f0ac59aa9a971825e1af"`);
        await queryRunner.query(`ALTER TABLE "lyrics" DROP CONSTRAINT "FK_1929e3cdc8b3e28106e773b16d6"`);
        await queryRunner.query(`ALTER TABLE "collaborators" DROP CONSTRAINT "FK_4c40b1058f7e2b07e2e8b5dc4a2"`);
        await queryRunner.query(`ALTER TABLE "collaborators" DROP CONSTRAINT "FK_8124c8d02e6d4729ebbd10f94fa"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP CONSTRAINT "FK_277ccc2a69a45fe1c39291b05bb"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP CONSTRAINT "FK_dc7e3bd7dd229d873f0d4a4b0e6"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP CONSTRAINT "FK_5789c0783b7d8fff2eda1e2b1a5"`);
        await queryRunner.query(`ALTER TABLE "songs" DROP CONSTRAINT "FK_3ea40af60e7deab5fe355995969"`);
        await queryRunner.query(`ALTER TABLE "release_containers" DROP CONSTRAINT "FK_0653392b8b9a0b778449afb8507"`);
        await queryRunner.query(`ALTER TABLE "release_containers" DROP CONSTRAINT "FK_81b31b9899b0dcf42037a0486c8"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_539df2da3266ea3be5107f73a4b"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_f7bd9114dc2849a90d39512911b"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_f31f88025417e09223ea9a66b0b"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP CONSTRAINT "FK_db724db1bc3d94ad5ba38518433"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_10f285d038feb767bf7c2da14b3"`);
        await queryRunner.query(`ALTER TABLE "password_reset_token" DROP CONSTRAINT "FK_a4e53583f7a8ab7d01cded46a41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a2a9ebf4ad76daa68a1928f56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad75ed868b666dc10ccd8ae856"`);
        await queryRunner.query(`DROP TABLE "song_featured_temp_artists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b69e21df84c9ad1d583b39ed7e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3748b7c54e518df2e26acfcc9"`);
        await queryRunner.query(`DROP TABLE "song_featured_artists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_324141f738c918793a4b925766"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4768f3456814c77f3f16346f64"`);
        await queryRunner.query(`DROP TABLE "release_container_featured_temp_artists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b391b3cae8cd5e3e097e914ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f642e9450e265bc8e8874c9fe"`);
        await queryRunner.query(`DROP TABLE "release_container_featured_artists"`);
        await queryRunner.query(`DROP INDEX "public"."idx_promo_cards_page"`);
        await queryRunner.query(`DROP TABLE "promo_cards"`);
        await queryRunner.query(`DROP INDEX "public"."idx_presave_signups_page_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_presave_signups_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_presave_signups_platform"`);
        await queryRunner.query(`DROP TABLE "presave_signups"`);
        await queryRunner.query(`DROP TYPE "public"."presave_signups_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."presave_signups_platform_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ratedfans_links_page_platform"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ratedfans_links_active"`);
        await queryRunner.query(`DROP TABLE "ratedfans_links"`);
        await queryRunner.query(`DROP TYPE "public"."ratedfans_links_platform_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ratedfans_pages_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ratedfans_pages_artist_song"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ratedfans_pages_published"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95f5b723edb71e0b2425899cb5"`);
        await queryRunner.query(`DROP TABLE "ratedfans_pages"`);
        await queryRunner.query(`DROP TYPE "public"."ratedfans_pages_releasetype_enum"`);
        await queryRunner.query(`DROP TABLE "payout_methods"`);
        await queryRunner.query(`DROP TYPE "public"."payout_methods_type_enum"`);
        await queryRunner.query(`DROP TABLE "split_sheet_entries"`);
        await queryRunner.query(`DROP TYPE "public"."split_sheet_entries_status_enum"`);
        await queryRunner.query(`DROP TABLE "split_sheets"`);
        await queryRunner.query(`DROP TYPE "public"."split_sheets_status_enum"`);
        await queryRunner.query(`DROP TABLE "file_chunks"`);
        await queryRunner.query(`DROP TABLE "video_files"`);
        await queryRunner.query(`DROP TYPE "public"."video_files_quality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."video_files_format_enum"`);
        await queryRunner.query(`DROP TYPE "public"."video_files_validationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."video_files_status_enum"`);
        await queryRunner.query(`DROP TABLE "image_files"`);
        await queryRunner.query(`DROP TYPE "public"."image_files_sizetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."image_files_format_enum"`);
        await queryRunner.query(`DROP TYPE "public"."image_files_validationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."image_files_status_enum"`);
        await queryRunner.query(`DROP TABLE "audio_files"`);
        await queryRunner.query(`DROP TYPE "public"."audio_files_quality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audio_files_format_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audio_files_validationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audio_files_status_enum"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_validationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."files_status_enum"`);
        await queryRunner.query(`DROP TABLE "lyrics"`);
        await queryRunner.query(`DROP TABLE "collaborators"`);
        await queryRunner.query(`DROP TYPE "public"."collaborators_role_enum"`);
        await queryRunner.query(`DROP TABLE "songs"`);
        await queryRunner.query(`DROP TYPE "public"."songs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."songs_releasetype_enum"`);
        await queryRunner.query(`DROP TABLE "release_containers"`);
        await queryRunner.query(`DROP TYPE "public"."release_containers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."release_containers_type_enum"`);
        await queryRunner.query(`DROP TABLE "temp_artists"`);
        await queryRunner.query(`DROP TABLE "artists"`);
        await queryRunner.query(`DROP TABLE "labels"`);
        await queryRunner.query(`DROP TABLE "otp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d1613f95c6a564a3b588d161a"`);
        await queryRunner.query(`DROP TABLE "email_verification_tokens"`);
        await queryRunner.query(`DROP TABLE "password_reset_token"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_subscription_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
