export enum CollaboratorType {
  ARTIST = 'ARTIST',
  WRITER = 'WRITER',
  PRODUCER = 'PRODUCER',
  EXTERNAL = 'EXTERNAL',
  LABEL_ARTIST = 'LABEL_ARTIST',
}

export enum SplitType {
  WRITING = 'WRITING',
  PERFORMANCE = 'PERFORMANCE',
  PRODUCTION = 'PRODUCTION',
  PUBLISHING = 'PUBLISHING',
}
